//TODO: pinnata eliminacion tambien,si el usuario rechaza la metamask
//TODO: luego de la imagen conectar la creacion con el smart contract
//TODO: en el header dentro de la DAO poner el nombre de mi dao actual. Tambien que puedas customizar el color del header de mi dao... o mejor dicho, el color primario (o agregar a premium)

//TODO: Cambiar el button a las card que ya me he unido
//TODO: crear nuevo filtro para leer del localStorage todas mis DAOs que ya estoy unido

//?--- 11/12/2025 (jueves)---
//TODO: en el filtro del buscador de daos me toca meter la nueva categoria que lee las daos dentro del []
