//TODO: pinnata eliminacion tambien,si el usuario rechaza la metamask
//TODO: luego de la imagen conectar la creacion con el smart contract
//TODO: en el header dentro de la DAO poner el nombre de mi dao actual. Tambien que puedas customizar el color del header de mi dao... o mejor dicho, el color primario (o agregar a premium)

//TODO: agregar el funcionamiento del button de unirse a la DAO
//TODO: cambiar el titulo y color de la card de la daoGrid si eres creador, por ejemplo un borde llamativco
